'use strict';
// Stage the wall's fixture runs: fourteen run dirs shaped exactly as
// run-task.sh writes them, spread across four repos plus one run whose
// worktree is unreadable (the UNCHARTED tower), at every floor of the pipeline
// and owned by a mix of crew and the `bot` synthetic — one run per crew member
// the room has a character for, so every one of them can be looked at.
//
// The generated runs/ directory is committed, so `wall.sh --runs
// wall/fixtures/runs` and the demo storyboard work straight out of a clone.
// Re-run this to make the elapsed times read fresh again — it rewrites tracked
// files, so commit or discard the result. tests/wall.test.sh seeds its own copy
// into a temp dir instead of touching the repo.
//
// Usage: node wall/fixtures/seed.js [TARGET-DIR]   (default: ./runs beside this)

const fs = require('node:fs');
const path = require('node:path');

const DEFAULT_DEST = path.resolve(__dirname, 'runs');
const DEST = path.resolve(process.argv[2] || DEFAULT_DEST);
const MARKER = '.wall-fixtures';
const NOW = Math.floor(Date.now() / 1000);

const at = (ago) => String(NOW - ago);                                   // epoch, N seconds ago
const clk = (ago) => new Date((NOW - ago) * 1000).toTimeString().slice(0, 8); // local HH:MM:SS

// Where run-task.sh would have put the worktree for this ticket: the repo
// directory with the lowercased ticket appended, beside the repo (run-task.sh:59).
// The wall reverses exactly this to name the tower a run belongs to.
const worktreeFor = (project, id) => `/Users/angel/Projects/${project}-${id.toLowerCase()}`;

function write(id, name, body) {
  fs.writeFileSync(path.join(DEST, id, name), body.endsWith('\n') ? body : body + '\n');
}

// The files every run dir has, whatever stage it is in. `owner` is the crew
// member who dispatched it and `project` the repo it is working in — run-task.sh
// pins the first from HARNESS_OWNER and derives the second from the repo path.
// `worktree: 'result'` puts the path only in result.json (as a run that started
// before the pin existed would look), `'none'` leaves it unreadable entirely.
// `provider` is the implementer subscription the run is spending — the ops
// console's badge, and the one thing the stage text cannot tell you, since it
// says "Opus (Claude sub)" whichever provider is billed. `'none'` leaves the
// pin unwritten, as a run from before it existed.
function run({ id, project, owner, stageAge, totalAge, stage, activity, title, worktree,
  provider = 'anthropic' }) {
  fs.mkdirSync(path.join(DEST, id), { recursive: true });
  write(id, 'status', `${at(stageAge)} ${stage}`);
  write(id, 'started', at(totalAge));
  write(id, 'stages.log', `${at(totalAge)} __invocation__\n${at(stageAge)} ${stage}`);
  write(id, 'timeline', `${clk(stageAge)} ${stage}`);
  write(id, 'activity', activity);
  write(id, 'owner', owner);
  write(id, 'brief.md', `# ${title}\n\n- **Ticket**: ${id}\n`);
  if (!worktree) write(id, 'worktree', worktreeFor(project, id));
  if (provider !== 'none') write(id, 'implementer-provider', provider);
  write(id, 'base', 'origin/main');
}

function feed(id, lines) {
  write(id, 'feed.log', lines.map(([ago, text]) => `${clk(ago)} ${text}`).join('\n'));
}

function result(id, fields) {
  write(id, 'result.json', JSON.stringify({
    ticket: id, arm: 'full', implementer_model: 'opus', reviewer_model: 'gpt-5.6-sol',
    base: 'main', pr_url: '', demo_url: '', ...fields,
  }, null, 2));
}

// A typo in the optional target must not turn a fixture utility into a generic
// recursive delete. The repository's own fixture path is trusted; a custom
// path may be created from scratch, reused when it carries our marker, or be an
// already-empty directory. Anything else is somebody's data, so leave it alone.
if (fs.existsSync(DEST)) {
  const stat = fs.lstatSync(DEST);
  const entries = stat.isDirectory() ? fs.readdirSync(DEST) : [];
  const marked = stat.isDirectory() && entries.includes(MARKER);
  const disposable = DEST === DEFAULT_DEST || marked || (stat.isDirectory() && entries.length === 0);
  if (!disposable) {
    throw new Error(`refusing to replace unmarked fixture target: ${DEST}`);
  }
  fs.rmSync(DEST, { recursive: true });
}
fs.mkdirSync(DEST, { recursive: true });
fs.writeFileSync(path.join(DEST, MARKER), 'Generated by wall/fixtures/seed.js.\n');

// --- olyxbase: the busy tower — three floors lit and one shipped ---------------
run({
  id: 'OLYX-1631', project: 'olyxbase', owner: 'angel', stageAge: 145, totalAge: 1320,
  stage: 'implementing — Opus (Claude sub)',
  activity: '⏺ Edit src/invoices/export.ts',
  title: 'Invoice export endpoint — CSV + XLSX',
});
feed('OLYX-1631', [
  [900, '🧠 Reading the existing report handlers before touching the router'],
  [840, '⏺ Read src/invoices/report.ts'],
  [700, '⏺ Grep createWorkbook'],
  [610, '💬 Reusing the sheet builder from reports instead of writing a second one'],
  [520, '⏺ Write src/invoices/export.ts'],
  [430, '⏺ Edit src/invoices/router.ts'],
  [300, '⏺ Bash npm run test -- invoices'],
  [210, '🧠 The XLSX golden file wants the amounts as numbers, not strings'],
  [145, '⏺ Edit src/invoices/export.ts'],
]);

run({
  id: 'OLYX-1660', project: 'olyxbase', owner: 'angel', stageAge: 40, totalAge: 1800,
  stage: 'test gate #2 (deterministic — no model)',
  activity: 'test gate #2 (deterministic — no model)',
  title: 'Contract PDF footer — VAT line per jurisdiction',
});
write('OLYX-1660', 'gate-rounds.log', '1 fail');
feed('OLYX-1660', [
  [600, '⏺ Edit src/contracts/footer.tsx'],
  [430, '⏺ Bash npm run gate'],
  [300, '💬 Two snapshots still carry the old single-VAT footer — updating both'],
  [180, '⏺ Edit src/contracts/__snapshots__/footer.test.tsx.snap'],
  [40, '⏺ Bash npm run gate'],
]);

// The searchlight: this is the one run on the wall that wants a human.
run({
  id: 'OLYX-1642', project: 'olyxbase', owner: 'reinier', stageAge: 780, totalAge: 4020,
  stage: 'waiting — implementer needs your input (QUESTIONS.md)',
  activity: 'waiting — implementer needs your input (QUESTIONS.md)',
  title: 'Retire the legacy quote PDF renderer',
});
write('OLYX-1642', 'QUESTIONS.md', `# Questions

Legacy quotes still render through the old PDF pipeline. Keep it behind a
feature flag for existing quotes, or migrate them all in this release?

- Option A: flag it, migrate lazily on the next edit.
- Option B: one-shot backfill, delete the old renderer in this PR.
`);
feed('OLYX-1642', [
  [1500, '⏺ Read src/pdf/legacy-renderer.ts'],
  [1200, '🧠 The two renderers disagree on how historical quotes are stored'],
  [900, '⏺ Write .harness/QUESTIONS.md'],
  [780, '🏁 success'],
]);
result('OLYX-1642', {
  status: 'needs_input', owner: 'reinier', gate: 'not_run',
  branch: 'feat/retire-legacy-pdf', worktree: worktreeFor('olyxbase', 'OLYX-1642'),
  metrics: {
    wall_seconds: 4020, gate_rounds: [],
    diff: { files_changed: 3, insertions: 88, deletions: 12 },
  },
});

// Shipped an hour ago: its completion moment is long over, so it is in the
// snapshot but not in the skyline. Its worktree lives only in result.json — the
// run dir's pin is the primary source, this proves the fallback still names the
// tower.
run({
  id: 'OLYX-1598', project: 'olyxbase', owner: 'emre', stageAge: 3300, totalAge: 6100,
  stage: 'done: ready', activity: 'done: ready', worktree: 'result',
  title: 'Cache the dashboard KPI query',
});
write('OLYX-1598', 'gate-rounds.log', '1 fail\n2 pass');
feed('OLYX-1598', [
  [4200, '◆ codex Checkpoint 3 — the TTL belongs in config, not inline'],
  [3900, '◆ codex Moving 300 to CACHE_TTL_SECONDS in src/config/cache.ts'],
  [3600, '⏺ Bash npm run gate'],
  [3400, '🏁 success'],
  [3300, '⏺ Bash gh pr create --draft'],
]);
result('OLYX-1598', {
  status: 'ready', owner: 'emre', gate: 'pass', branch: 'feat/cache-kpi-query',
  worktree: worktreeFor('olyxbase', 'OLYX-1598'),
  pr_url: 'https://github.com/acme/dashboard/pull/812',
  demo_url: 'https://demo.example.net/OLYX-1598/demo.mp4',
  metrics: {
    wall_seconds: 2800,
    gate_rounds: [{ round: '1', result: 'fail' }, { round: '2', result: 'pass' }],
    opus_commits: 3, codex_commits: 2,
    diff: { files_changed: 7, insertions: 214, deletions: 63 },
    // The whole invocation's spend. `turns` is the column the ops console draws;
    // BOT-2287 below carries the implementer-only count instead, which is the
    // other shape the wall has to read.
    usage: {
      input_tokens: 41000, cache_read_input_tokens: 1840000,
      cache_creation_input_tokens: 96000, output_tokens: 38000, turns: 64,
    },
    // A run the third-vendor verifier scored: the plate chip and the SCORE
    // columns have something to render. LEGACY-0042 deliberately has none — it
    // predates result.json entirely and is the field-absent case.
    verifier: {
      score: 0.83, at_implementer: 0.71,
      criteria: [
        { name: 'The KPI query is cached', score: 0.91 },
        { name: 'The TTL is configurable', score: 0.74 },
      ],
      model: 'deepseek-v4-flash', provider: 'deepseek', evaluations: 3,
      steps: 61, elided_steps: 0,
      usage: { calls: 9, input_tokens: 184000, output_tokens: 900 },
      seconds: 71.4,
    },
  },
});

// --- two ships that carry what they spent ---------------------------------------
// The cost header's corpus: one finished run per provider, with the telemetry
// run-task.sh writes into metrics — the à-la-carte list price every run
// carries whatever the provider, and the z.ai credits only a GLM run does.
// OLYX-1598 and BOT-2287 above stay deliberately uncosted: the board's '—'
// and the summary's exclusion of a null cost from its sums both need a
// finished run that predates the figures.
run({
  id: 'OLYX-1676', project: 'valoryx-graphql-api', owner: 'emre', stageAge: 1200, totalAge: 3900,
  provider: 'zai', stage: 'done: ready', activity: 'done: ready',
  title: 'Webhook retries — drain the dead letter queue on a schedule',
});
write('OLYX-1676', 'gate-rounds.log', '1 pass');
feed('OLYX-1676', [
  [3300, '🧠 A retry queue nobody drains is an outage with extra steps'],
  [3000, '⏺ Write src/webhooks/drain.ts'],
  [2400, '◆ codex Backoff reset belongs in config, not in the drain loop'],
  [1900, '⏺ Edit src/webhooks/drain.ts'],
  [1500, '⏺ Bash npm run test -- webhooks'],
  [1300, '🏁 success'],
  [1200, '⏺ Bash gh pr create --draft'],
]);
result('OLYX-1676', {
  status: 'ready', owner: 'emre', gate: 'pass', branch: 'feat/webhook-dlq-drain',
  worktree: worktreeFor('valoryx-graphql-api', 'OLYX-1676'),
  pr_url: 'https://github.com/acme/valoryx-graphql-api/pull/1149',
  metrics: {
    wall_seconds: 3200,
    gate_rounds: [{ round: '1', result: 'pass' }],
    opus_commits: 3, codex_commits: 1,
    implementer_num_turns: 41,
    implementer_usage: {
      input_tokens: 780000, cache_read_input_tokens: 9570000,
      cache_creation_input_tokens: 240000, output_tokens: 400000,
    },
    total_cost_usd: 63.87,
    usage: {
      input_tokens: 780000, cache_read_input_tokens: 9570000,
      cache_creation_input_tokens: 240000, output_tokens: 400000,
      turns: 41, zai_credits_est: 3125.1,
    },
    diff: { files_changed: 9, insertions: 342, deletions: 71 },
  },
});

run({
  id: 'OLYX-1681', project: 'olyxbase', owner: 'angel', stageAge: 2000, totalAge: 4800,
  stage: 'done: ready', activity: 'done: ready',
  title: 'Invoice export — stream the XLSX instead of buffering it',
});
write('OLYX-1681', 'gate-rounds.log', '1 pass');
feed('OLYX-1681', [
  [4200, '⏺ Read src/invoices/export.ts'],
  [3800, '🧠 The workbook is built whole in memory — one quarter of them is 2 GB'],
  [3200, '⏺ Write src/invoices/sheet-stream.ts'],
  [2600, '⏺ Edit src/invoices/export.ts'],
  [2200, '⏺ Bash npm run test -- invoices'],
  [2000, '🏁 success'],
]);
result('OLYX-1681', {
  status: 'ready', owner: 'angel', gate: 'pass', branch: 'feat/stream-invoice-xlsx',
  worktree: worktreeFor('olyxbase', 'OLYX-1681'),
  pr_url: 'https://github.com/acme/dashboard/pull/815',
  metrics: {
    wall_seconds: 4100,
    gate_rounds: [{ round: '1', result: 'pass' }],
    opus_commits: 4, codex_commits: 0,
    implementer_num_turns: 63,
    implementer_usage: {
      input_tokens: 121000, cache_read_input_tokens: 4100000,
      cache_creation_input_tokens: 150000, output_tokens: 96000,
    },
    total_cost_usd: 19.52,
    usage: {
      input_tokens: 121000, cache_read_input_tokens: 4100000,
      cache_creation_input_tokens: 150000, output_tokens: 96000,
      turns: 63,
    },
    diff: { files_changed: 11, insertions: 508, deletions: 122 },
  },
});

// --- olyx-agents: a review in flight, the synthetic's own two runs -------------
run({
  id: 'OLYX-1655', project: 'olyx-agents', owner: 'angel', stageAge: 95, totalAge: 2460,
  stage: 'review — Codex (ChatGPT sub)',
  activity: '◆ codex reviewing the diff against origin/main',
  title: 'Broker payout ledger — split by desk',
});
write('OLYX-1655', 'gate-rounds.log', '1 pass');
feed('OLYX-1655', [
  [700, '⏺ Bash npm run gate'],
  [640, '🏁 success'],
  [420, '◆ codex Reading .harness/brief.md and the diff against origin/main'],
  [330, '◆ codex Checkpoint 1 — no tests weakened, fixtures untouched'],
  [240, '◆ codex ledger.ts duplicates roundToCents from money.ts — folding it back'],
  [150, '◆ codex Applying patch to src/ledger/split.ts'],
  [95, '◆ codex Re-running the gate after the refactor'],
]);

run({
  id: 'BOT-2291', project: 'olyx-agents', owner: 'bot', stageAge: 55, totalAge: 900, provider: 'zai',
  stage: 'base sync — merge latest main (script — no model)',
  activity: 'base sync — merge latest main (script — no model)',
  title: 'Nightly dependency sweep — bump and verify',
});
feed('BOT-2291', [
  [700, '⏺ Bash npm outdated'],
  [560, '💬 11 packages behind; 3 are majors — holding those back for a human'],
  [400, '⏺ Edit package.json'],
  [240, '⏺ Bash npm install --package-lock-only'],
  [55, '⏺ Bash git merge origin/main'],
]);

run({
  id: 'BOT-2287', project: 'olyx-agents', owner: 'bot', stageAge: 5400, totalAge: 8200,
  stage: 'done: rejected', activity: 'done: rejected',
  title: 'Nightly refactor sweep — dedupe the money helpers',
});
write('BOT-2287', 'gate-rounds.log', '1 pass');
write('BOT-2287', 'REJECTED.md', `# Rejected

The sweep rewrote rounding at three call sites to share one helper, but billing
and payouts round in opposite directions on purpose. Collapsing them is a
pricing decision, not a refactor.
`);
feed('BOT-2287', [
  [6000, '◆ codex Reading src/money/round.ts and both call sites'],
  [5700, '◆ codex billing rounds half-up, payouts round half-down — deliberate'],
  [5400, '◆ codex Writing .harness/REJECTED.md instead of papering over it'],
]);
result('BOT-2287', {
  status: 'rejected', owner: 'bot', gate: 'pass', branch: 'chore/dedupe-money-helpers',
  worktree: worktreeFor('olyx-agents', 'BOT-2287'),
  metrics: {
    wall_seconds: 2800, gate_rounds: [{ round: '1', result: 'pass' }],
    opus_commits: 2, codex_commits: 0,
    implementer_num_turns: 37,
    diff: { files_changed: 5, insertions: 131, deletions: 47 },
    // A green gate and a rejection: exactly the run whose score is worth having,
    // and the reason the verifier scores the rejected arm too.
    verifier: {
      score: 0.24, at_implementer: 0.31,
      criteria: [{ name: 'The money helpers are deduplicated', score: 0.18 }],
      model: 'deepseek-v4-flash', provider: 'deepseek', evaluations: 3,
      steps: 44, elided_steps: 0,
      usage: { calls: 6, input_tokens: 120000, output_tokens: 600 },
      seconds: 48.2,
    },
  },
});

// --- valoryx-graphql-api: one implementing, one on the roof --------------------
run({
  id: 'OLYX-1648', project: 'valoryx-graphql-api', owner: 'reinier', stageAge: 260, totalAge: 2100,
  stage: 'implementing — Opus (Claude sub)', provider: 'zai',
  activity: '⏺ Write src/webhooks/retry-queue.ts',
  title: 'Webhook retries — exponential backoff with a dead letter queue',
});
feed('OLYX-1648', [
  [1400, '⏺ Read src/webhooks/dispatch.ts'],
  [1100, '🧠 Retries are inline today, so one slow endpoint stalls the whole batch'],
  [800, '⏺ Write src/webhooks/retry-queue.ts'],
  [520, '⏺ Bash npm run test -- webhooks'],
  [260, '⏺ Write src/webhooks/retry-queue.ts'],
]);

run({
  id: 'OLYX-1673', project: 'valoryx-graphql-api', owner: 'emre', stageAge: 20, totalAge: 600,
  stage: 'push + draft PR (script — no model)',
  activity: 'push + draft PR (script — no model)',
  title: 'Dashboard filters — persist the last used range',
});
write('OLYX-1673', 'gate-rounds.log', '1 pass');
feed('OLYX-1673', [
  [420, '⏺ Edit src/dashboard/filters.tsx'],
  [300, '⏺ Bash npm run gate'],
  [190, '🏁 success'],
  [20, '⏺ Bash gh pr create --draft'],
]);

// --- olyx-dashboard: an adhoc ticket mid-demo, and Ran's ----------------------
// The room draws whoever dispatched a run, so the fixtures need one run per
// crew member the wall has a character for or `?shot=room&run=<id>` cannot be
// pointed at all of them. This one goes on a tower that already stands and has
// room on it: a fifth repo would have been a new tower rather than a new
// person, and a third live run on either of the busy two would have made a
// second crowded tower out of a fixture set that means to have exactly one.
run({
  id: 'OLYX-1667', project: 'olyx-dashboard', owner: 'ran', stageAge: 110, totalAge: 1650,
  stage: 'implementing — Opus (Claude sub)',
  activity: '⏺ Edit src/views/saved-layout.ts',
  title: 'Saved views — per-user dashboard layouts',
});
feed('OLYX-1667', [
  [1200, '⏺ Read src/views/layout-store.ts'],
  [980, '🧠 Layouts are per workspace today, so two people fight over one grid'],
  [720, '⏺ Grep useLayout'],
  [430, '💬 Keying the store by user and falling back to the workspace default'],
  [110, '⏺ Edit src/views/saved-layout.ts'],
]);

run({
  id: 'adhoc-kpi-sparklines', project: 'olyx-dashboard', owner: 'angel',
  stageAge: 30, totalAge: 1500,
  stage: 'demo — recording (script, no model)',
  activity: 'demo — recording (script, no model)',
  title: 'Sparklines on the KPI tiles',
});
write('adhoc-kpi-sparklines', 'gate-rounds.log', '1 pass');
feed('adhoc-kpi-sparklines', [
  [900, '⏺ Write src/kpi/Sparkline.tsx'],
  [560, '⏺ Bash npm run gate'],
  [400, '🏁 success'],
  [30, '⏺ Bash shot-scraper video .harness/demo.yml'],
]);

// --- no readable worktree: the UNCHARTED tower --------------------------------
// A run dir that predates the worktree pin, or one interrupted before setup
// wrote it. The wall will not invent a repo for it.
run({
  id: 'LEGACY-0042', project: '', owner: '', stageAge: 210, totalAge: 3600,
  stage: 'implementing — Opus (Claude sub)', worktree: 'none', provider: 'none',
  activity: '⏺ Edit lib/importer/csv.rb',
  title: 'Importer — tolerate BOM-prefixed CSV headers',
});
feed('LEGACY-0042', [
  [1200, '⏺ Read lib/importer/csv.rb'],
  [800, '🧠 The BOM survives the encoding sniff and lands in the first header'],
  [210, '⏺ Edit lib/importer/csv.rb'],
]);

const seeded = fs.readdirSync(DEST).filter((e) => e !== MARKER).length;
console.log(`seeded ${seeded} fixture runs in ${DEST}`);
